#!/usr/bin/env bash
export BASE_DIR=$(pwd)
export REGION=us-central1

# Shared VPC Config
export NETWORK=cda-vpc
export SUBNET1=tier-1
export SUBNET2=tier-2
export SUBNET3=serverless-subnet

# IAP Setup used by iap/enable_iap.sh
export DISPLAY_NAME="cda-ui"
export IAP_SECRET_NAME="cda-iap-secret"
export SA_START_PIPELINE="serviceAccount:cloudrun-startpipeline-sa@${PROJECT_ID}.iam.gserviceaccount.com"
export SA_QUEUE="serviceAccount:cloudrun-queue-sa@${PROJECT_ID}.iam.gserviceaccount.com"
export APPLICATION_NAME="CDA Application"

# Terraform Variable
export TF_LOG_PATH="$BASE_DIR"/tf.log
#export TF_LOG="DEBUG"
export TF_VAR_api_domain=$API_DOMAIN
export TF_VAR_project_id=$PROJECT_ID
export TF_VAR_docai_project_id=${DOCAI_PROJECT_ID:-$PROJECT_ID}
export TF_BUCKET_NAME="${PROJECT_ID}-tfstate"
export TF_BUCKET_LOCATION="us"
export TF_VAR_config_bucket="${PROJECT_ID}-config"
export TF_VAR_region=$REGION
export TF_VAR_iap_secret_name="${IAP_SECRET_NAME}"

# used by Microservices
export CONFIG_BUCKET=${TF_VAR_config_bucket}
export DEBUG=True

echo "Using       PROJECT_ID=$TF_VAR_project_id, CONFIG_BUCKET=$CONFIG_BUCKET, API_DOMAIN=$TF_VAR_api_domain"
echo "(Optional)  HOST_PROJECT_ID=$HOST_PROJECT_ID, DOCAI_PROJECT_ID=$TF_VAR_docai_project_id"
