#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -z "${PROJECT_ID}" ]]; then
  echo PROJECT_ID env variable is not set.  | tee -a "$LOG"
  exit
fi

###################################
# DOCAI WH Project - GCP Project in which DocAI WH has been provisioned
export DOCAI_WH_PROJECT_ID=${DOCAI_WH_PROJECT_ID:-$PROJECT_ID}
export DOCAI_WH_PROJECT_NUMBER=$(gcloud projects describe  "${DOCAI_WH_PROJECT_ID}" --format='get(projectNumber)')
export SA_DOCAI_WH="service-${DOCAI_WH_PROJECT_NUMBER}@gcp-sa-cloud-cw.iam.gserviceaccount.com"
gcloud config set project $DOCAI_WH_PROJECT_ID

# Service Account to execute script
export SA_NAME=docai-utility-sa
export SA_EMAIL=${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
export KEY_NAME=${PROJECT_ID}_${SA_NAME}.json
export KEY_PATH=${DIR}/${KEY_NAME}
export CALLER_USER=${SA_EMAIL}


###################################
# DOCAI Project - GCP Project with DocAI Processor used for document parsing
export DOCAI_PROJECT_ID=${DOCAI_PROJECT_ID:-$PROJECT_ID}
export DOCAI_PROJECT_NUMBER=$(gcloud projects describe  "${DOCAI_PROJECT_ID}" --format='get(projectNumber)')
export DOCAI_OUTPUT_BUCKET="$PROJECT_ID-docai-output"
export SA_DOCAI="service-${DOCAI_PROJECT_NUMBER}@gcp-sa-prod-dai-core.iam.gserviceaccount.com"


###################################
# PROJECT with GCS Data to be Loaded
export DATA_PROJECT_ID=${DATA_PROJECT_ID:-$PROJECT_ID}             # Project ID of the GCP Project in which GCS bucket is located for data to be loaded into the DW.


# Additional parameters
export DEBUG=true

echo "DOCAI_WH_PROJECT_ID=$DOCAI_WH_PROJECT_ID, DOCAI_PROJECT_ID=$DOCAI_PROJECT_ID, DATA_PROJECT_ID=$DATA_PROJECT_ID"