SELECT * FROM `.validation.entities`
                  PIVOT
                  (STRING_AGG(value, ",") as _,
                   STRING_AGG(corrected_value, ",") as corrected,
                   AVG(confidence) as conf
 FOR name IN (
  'beneficiaryAddress',
  'beneficiaryDoB',
  'beneficiaryLanguage',
  'beneficiaryName',
  'beneficiaryPhone',
  'beneficiaryPlanNumber',
  'beneficiaryState',
  'beneficiaryZip',
  'dateLastAuthorized',
  'diagCode',
  'diagDescription',
  'ipaResponsibility',
  'issurerName',
  'memberEffectiveDate',
  'modificationFax',
  'prevAuthNumber',
  'procCode',
  'procDesc',
  'referralRequestedBy',
  'retroFax',
  'routineFax',
  'rpFax',
  'rpJustification',
  'rpName',
  'rpNpi',
  'rpPhone',
  'rpSign',
  'rpSpecialty',
  'spAddress',
  'spFacilityName',
  'spFax1',
  'spFax2',
  'spName',
  'spNpi',
  'spPhone2',
  'spRequestDate',
  'urgentFax'
)) AS fields
Where document_class="pa_form_cda"